export const customizedComponents = {
  accordion: [
    { title: "Default", type: "accordion", name: "accordion-01" },
    { title: "Outline", type: "accordion", name: "accordion-02" },
    { title: "Box", type: "accordion", name: "accordion-03" },
    { title: "Contained", type: "accordion", name: "accordion-04" },
    {
      title: "Box Contained",
      type: "accordion",
      name: "accordion-05",
    },
    {
      title: "Tabs",
      type: "accordion",
      name: "accordion-06",
    },
    {
      title: "Highlight Active Item",
      type: "accordion",
      name: "accordion-07",
    },
    {
      title: "Multiple expanded at a time",
      type: "accordion",
      name: "accordion-08",
    },
    {
      title: "Expand Icon",
      type: "accordion",
      name: "accordion-09",
    },
    {
      title: "Icon",
      type: "accordion",
      name: "accordion-10",
    },
    {
      title: "Media Content",
      type: "accordion",
      name: "accordion-11",
    },
    {
      title: "Disabled Item",
      type: "accordion",
      name: "accordion-12",
    },
  ],
  alert: [
    { title: "Primary", type: "alert", name: "alert-01" },
    { title: "Destructive", type: "alert", name: "alert-02" },
    { title: "Success", type: "alert", name: "alert-03" },
    { title: "Warning", type: "alert", name: "alert-04" },
    { title: "Info", type: "alert", name: "alert-05" },
    { title: "With background", type: "alert", name: "alert-06" },
    { title: "Soft", type: "alert", name: "alert-07" },
    { title: "Bootstrap", type: "alert", name: "alert-08" },
    { title: "Callout", type: "alert", name: "alert-09" },
    { title: "With actions", type: "alert", name: "alert-10" },
  ],
  "alert-dialog": [
    { title: "Default", type: "alert-dialog", name: "alert-dialog-01" },
    { title: "With Icon", type: "alert-dialog", name: "alert-dialog-02" },
    { title: "Destructive", type: "alert-dialog", name: "alert-dialog-03" },
    {
      title: "Info",
      type: "alert-dialog",
      name: "alert-dialog-04",
    },
    {
      title: "Customized Header",
      type: "alert-dialog",
      name: "alert-dialog-05",
    },
    {
      title: "Customized Footer",
      type: "alert-dialog",
      name: "alert-dialog-06",
    },
  ],
  avatar: [
    { title: "Default", type: "avatar", name: "avatar-01" },
    {
      title: "Clickable",
      type: "avatar",
      name: "avatar-02",
    },
    {
      title: "Tooltip",
      type: "avatar",
      name: "avatar-03",
    },
    {
      title: "With Text",
      type: "avatar",
      name: "avatar-04",
    },
    { title: "Hover Card", type: "avatar", name: "avatar-05" },
    { title: "Size", type: "avatar", name: "avatar-06" },
    { title: "Color", type: "avatar", name: "avatar-07" },
    { title: "Shape", type: "avatar", name: "avatar-08" },
    { title: "Fallback", type: "avatar", name: "avatar-09" },
    { title: "With Ring", type: "avatar", name: "avatar-10" },
    { title: "Status", type: "avatar", name: "avatar-11" },
    { title: "Group", type: "avatar", name: "avatar-12" },
    { title: "Group max avatar", type: "avatar", name: "avatar-13" },
  ],
  badge: [
    { title: "Default", type: "badge", name: "badge-01" },
    { title: "Secondary", type: "badge", name: "badge-02" },
    { title: "Outline", type: "badge", name: "badge-03" },
    { title: "Destructive", type: "badge", name: "badge-04" },
    { title: "Rounded", type: "badge", name: "badge-05" },
    { title: "Gradient", type: "badge", name: "badge-06" },
    { title: "Gradient Outline", type: "badge", name: "badge-07" },
    { title: "Soft", type: "badge", name: "badge-08" },
    { title: "Status", type: "badge", name: "badge-09" },
    { title: "With image", type: "badge", name: "badge-10" },
    { title: "With icon", type: "badge", name: "badge-11" },
    { title: "Clickable", type: "badge", name: "badge-12" },
    { title: "Clickable link", type: "badge", name: "badge-13" },
  ],
  breadcrumb: [
    { title: "Default", type: "breadcrumb", name: "breadcrumb-01" },
    {
      title: "Slash Separator",
      type: "breadcrumb",
      name: "breadcrumb-02",
    },
    {
      title: "Chevrons Separator",
      type: "breadcrumb",
      name: "breadcrumb-03",
    },
    { title: "Dot Separator", type: "breadcrumb", name: "breadcrumb-04" },
    {
      title: "With Icon",
      type: "breadcrumb",
      name: "breadcrumb-05",
    },
    {
      title: "With Icon 2",
      type: "breadcrumb",
      name: "breadcrumb-06",
    },
    {
      title: "With Icon and Label",
      type: "breadcrumb",
      name: "breadcrumb-07",
    },
    {
      title: "With Icon and Label 2",
      type: "breadcrumb",
      name: "breadcrumb-08",
    },
    {
      title: "With Background",
      type: "breadcrumb",
      name: "breadcrumb-09",
    },
    {
      title: "Tab Active",
      type: "breadcrumb",
      name: "breadcrumb-10",
    },
    {
      title: "Tabs",
      type: "breadcrumb",
      name: "breadcrumb-11",
    },
    {
      title: "Tabs Outline",
      type: "breadcrumb",
      name: "breadcrumb-12",
    },
    {
      title: "With Dropdown",
      type: "breadcrumb",
      name: "breadcrumb-13",
    },
    {
      title: "Collapsed",
      type: "breadcrumb",
      name: "breadcrumb-14",
    },
    {
      title: "Steps",
      type: "breadcrumb",
      name: "breadcrumb-15",
    },
  ],
  button: [
    { title: "Primary", type: "button", name: "button-01" },
    { title: "Secondary", type: "button", name: "button-02" },
    { title: "Destructive", type: "button", name: "button-03" },
    { title: "Outline", type: "button", name: "button-04" },
    { title: "Icon", type: "button", name: "button-05" },
    { title: "Loading", type: "button", name: "button-06" },
    { title: "Split Button", type: "button", name: "button-07" },
    { title: "Ghost", type: "button", name: "button-08" },
    { title: "Gradient", type: "button", name: "button-09" },
    { title: "Link", type: "button", name: "button-10" },
    { title: "Social", type: "button", name: "button-11" },
    { title: "Social Login", type: "button", name: "button-12" },
    { title: "Neon", type: "button", name: "button-13" },
    { title: "Rounded", type: "button", name: "button-14" },
    { title: "Toggle", type: "button", name: "button-15" },
    { title: "Theme Toggle", type: "button", name: "button-16" },
    { title: "Full Width", type: "button", name: "button-17" },
    { title: "Group", type: "button", name: "button-18" },
    { title: "Group 2", type: "button", name: "button-19" },
    { title: "Copy Button", type: "button", name: "button-20" },
    { title: "With badge", type: "button", name: "button-21" },
    { title: "With tooltip", type: "button", name: "button-22" },
    { title: "With tap animation", type: "button", name: "button-23" },
  ],
  card: [
    { title: "Default", type: "card", name: "card-01" },
    { title: "With background", type: "card", name: "card-02" },
    { title: "Sign Up", type: "card", name: "card-03" },
    { title: "Banner", type: "card", name: "card-04" },
    { title: "Pricing", type: "card", name: "card-05" },
    { title: "Post", type: "card", name: "card-06" },
    { title: "Product", type: "card", name: "card-07" },
    { title: "Testimonial", type: "card", name: "card-08" },
  ],
  carousel: [
    { title: "Default", type: "carousel", name: "carousel-01" },
    { title: "Multiple slides", type: "carousel", name: "carousel-02" },
    { title: "Vertical", type: "carousel", name: "carousel-03" },
    { title: "Slide Status", type: "carousel", name: "carousel-04" },
    { title: "Slide Status 2", type: "carousel", name: "carousel-05" },
    { title: "Pagination", type: "carousel", name: "carousel-06" },
    { title: "Footer", type: "carousel", name: "carousel-07" },
    { title: "Progress", type: "carousel", name: "carousel-08" },
    { title: "Thumbs", type: "carousel", name: "carousel-09" },
    { title: "Opacity", type: "carousel", name: "carousel-10" },
    { title: "Scale", type: "carousel", name: "carousel-11" },
  ],
  checkbox: [
    { title: "With Text", type: "checkbox", name: "checkbox-01" },
    { title: "Disabled", type: "checkbox", name: "checkbox-02" },
    { title: "Indeterminate", type: "checkbox", name: "checkbox-03" },
    { title: "Horizontal Group", type: "checkbox", name: "checkbox-04" },
    { title: "Vertical Group", type: "checkbox", name: "checkbox-05" },
    { title: "Controlled", type: "checkbox", name: "checkbox-06" },
    { title: "Colors", type: "checkbox", name: "checkbox-07" },
    { title: "Sizes", type: "checkbox", name: "checkbox-08" },
    { title: "Icon", type: "checkbox", name: "checkbox-09" },
    {
      title: "Multi Color Picker",
      type: "checkbox",
      name: "checkbox-10",
    },
    { title: "Card", type: "checkbox", name: "checkbox-11" },
    { title: "With form", type: "checkbox", name: "checkbox-12" },
  ],
  collapsible: [
    { title: "Default", type: "collapsible", name: "collapsible-01" },
    { title: "Show More", type: "collapsible", name: "collapsible-02" },
    { title: "File Tree", type: "collapsible", name: "collapsible-03" },
    { title: "Filters", type: "collapsible", name: "collapsible-04" },
  ],
  "dropdown-menu": [
    { title: "Default", type: "dropdown-menu", name: "dropdown-menu-01" },
    { title: "With Icon", type: "dropdown-menu", name: "dropdown-menu-02" },
    { title: "Checkboxes", type: "dropdown-menu", name: "dropdown-menu-03" },
    { title: "Radio Group", type: "dropdown-menu", name: "dropdown-menu-04" },
    {
      title: "With Sub Menu",
      type: "dropdown-menu",
      name: "dropdown-menu-05",
    },
    {
      title: "With Shortcuts",
      type: "dropdown-menu",
      name: "dropdown-menu-06",
    },
    {
      title: "Complex Menu",
      type: "dropdown-menu",
      name: "dropdown-menu-07",
    },
    {
      title: "Workspace Switcher",
      type: "dropdown-menu",
      name: "dropdown-menu-08",
    },
  ],
  input: [
    { title: "Default", type: "input", name: "input-01" },
    { title: "With ring", type: "input", name: "input-02" },
    { title: "Filled", type: "input", name: "input-03" },
    { title: "Disabled", type: "input", name: "input-04" },
    { title: "With label", type: "input", name: "input-05" },
    { title: "With button", type: "input", name: "input-06" },
    { title: "With adornments", type: "input", name: "input-07" },
    { title: "With helper text", type: "input", name: "input-08" },
    { title: "With error message", type: "input", name: "input-09" },
    { title: "With form", type: "input", name: "input-10" },
    { title: "File input", type: "input", name: "input-11" },
    { title: "Dropzone", type: "input", name: "input-12" },
  ],
  "input-otp": [
    { title: "Default", type: "input-otp", name: "input-otp-01" },
    {
      title: "Without Separator",
      type: "input-otp",
      name: "input-otp-02",
    },
    { title: "Separated", type: "input-otp", name: "input-otp-03" },
    {
      title: "Separated 2",
      type: "input-otp",
      name: "input-otp-04",
    },
    { title: "Secondary", type: "input-otp", name: "input-otp-05" },
    { title: "Custom Separator", type: "input-otp", name: "input-otp-06" },
    { title: "Inner Shadow", type: "input-otp", name: "input-otp-07" },
  ],
  "navigation-menu": [
    { title: "Default", type: "navigation-menu", name: "navigation-menu-01" },
    { title: "With Icon", type: "navigation-menu", name: "navigation-menu-02" },
    {
      title: "Dropdown",
      type: "navigation-menu",
      name: "navigation-menu-03",
      className: "col-span-full",
    },
    {
      title: "Active Item",
      type: "navigation-menu",
      name: "navigation-menu-04",
    },
    {
      title: "Underlined",
      type: "navigation-menu",
      name: "navigation-menu-05",
    },
    {
      title: "Rich Navigation Menu",
      type: "navigation-menu",
      name: "navigation-menu-06",
      className: "col-span-full",
    },
    { title: "Icon", type: "navigation-menu", name: "navigation-menu-07" },
    {
      title: "Mobile Navigation",
      type: "navigation-menu",
      name: "navigation-menu-08",
    },
  ],
  pagination: [
    { title: "Default", type: "pagination", name: "pagination-01" },
    {
      title: "Primary Button",
      type: "pagination",
      name: "pagination-02",
    },
    {
      title: "Secondary Button",
      type: "pagination",
      name: "pagination-03",
    },
    { title: "Rounded Button", type: "pagination", name: "pagination-04" },
    {
      title: "With Icon",
      type: "pagination",
      name: "pagination-05",
    },
    {
      title: "First and Last Page Buttons",
      type: "pagination",
      name: "pagination-06",
    },
    {
      title: "Bordered",
      type: "pagination",
      name: "pagination-07",
    },
    {
      title: "Tabs",
      type: "pagination",
      name: "pagination-08",
    },
    {
      title: "Tabs Secondary",
      type: "pagination",
      name: "pagination-09",
    },
    {
      title: "With Icon and Label",
      type: "pagination",
      name: "pagination-10",
    },
    {
      title: "Numberless Pagination",
      type: "pagination",
      name: "pagination-11",
    },
    {
      title: "Numberless with Text",
      type: "pagination",
      name: "pagination-12",
    },
    { title: "With ellipsis", type: "pagination", name: "pagination-13" },
    {
      title: "Table Pagination",
      type: "pagination",
      name: "pagination-14",
    },
  ],
  progress: [
    { title: "Default", type: "progress", name: "progress-01" },
    { title: "Linear with label", type: "progress", name: "progress-02" },
    { title: "Linear color", type: "progress", name: "progress-03" },
    {
      title: "Rounded progress indicator",
      type: "progress",
      name: "progress-04",
    },
    { title: "Gradient", type: "progress", name: "progress-05" },
    { title: "Animation", type: "progress", name: "progress-06" },
    { title: "Circular", type: "progress", name: "progress-07" },
    {
      title: "Circular with label",
      type: "progress",
      name: "progress-08",
    },
    {
      title: "Circular with custom label",
      type: "progress",
      name: "progress-09",
    },
    { title: "Circular color", type: "progress", name: "progress-10" },
    {
      title: "Circular progress shape",
      type: "progress",
      name: "progress-11",
    },
    {
      title: "Circular stroke width",
      type: "progress",
      name: "progress-12",
    },
  ],
  "radio-group": [
    { title: "Default", type: "radio-group", name: "radio-group-01" },
    { title: "Horizontal", type: "radio-group", name: "radio-group-02" },
    { title: "Disabled", type: "radio-group", name: "radio-group-03" },
    { title: "Color", type: "radio-group", name: "radio-group-04" },
    { title: "Size", type: "radio-group", name: "radio-group-05" },
    { title: "Variant", type: "radio-group", name: "radio-group-06" },
    { title: "Cards 1", type: "radio-group", name: "radio-group-07" },
    { title: "Cards 2", type: "radio-group", name: "radio-group-08" },
    { title: "Cards 3", type: "radio-group", name: "radio-group-09" },
  ],
  select: [
    { title: "Default", type: "select", name: "select-01" },
    { title: "Background Color", type: "select", name: "select-02" },
    { title: "Ghost", type: "select", name: "select-03" },
    {
      title: "Custom dropdown icon",
      type: "select",
      name: "select-04",
    },
    { title: "Shape", type: "select", name: "select-05" },
    { title: "With an icon", type: "select", name: "select-06" },
    { title: "With form", type: "select", name: "select-07" },
    { title: "Theme Selector", type: "select", name: "select-08" },
    {
      title: "Select menu position",
      type: "select",
      name: "select-09",
    },
    { title: "Scrollable", type: "select", name: "select-10" },
    { title: "Controlled", type: "select", name: "select-11" },
    { title: "With auto complete", type: "select", name: "select-12" },
  ],
  separator: [
    { title: "Default", type: "separator", name: "separator-01" },
    {
      title: "Horizontal separator with label",
      type: "separator",
      name: "separator-02",
    },
    {
      title: "Horizontal separator with chip",
      type: "separator",
      name: "separator-03",
    },
    { title: "Dashed", type: "separator", name: "separator-04" },
    { title: "Vertical", type: "separator", name: "separator-05" },
    {
      title: "Vertical with chip",
      type: "separator",
      name: "separator-06",
    },
  ],
  slider: [
    { title: "Default", type: "slider", name: "slider-01" },
    { title: "Disabled", type: "slider", name: "slider-02" },
    { title: "Size", type: "slider", name: "slider-03" },
    { title: "Color", type: "slider", name: "slider-04" },
    { title: "Shape", type: "slider", name: "slider-05" },
    { title: "With label", type: "slider", name: "slider-06" },
    { title: "Thumb Icon", type: "slider", name: "slider-07" },
    { title: "Audio Slider", type: "slider", name: "slider-08" },
    { title: "Marks", type: "slider", name: "slider-09" },
    { title: "Sticky label", type: "slider", name: "slider-10" },
    {
      title: "Sticky Label on Hover",
      type: "slider",
      name: "slider-11",
    },
    {
      title: "Sticky Label with Arrow",
      type: "slider",
      name: "slider-12",
    },
    { title: "Vertical", type: "slider", name: "slider-13" },
    { title: "Range", type: "slider", name: "slider-14" },
    { title: "Multiple Thumbs", type: "slider", name: "slider-15" },
  ],
  spinner: [
    { title: "Default", type: "spinner", name: "spinner-01" },
    { title: "Circle", type: "spinner", name: "spinner-02" },
    { title: "Pinwheel", type: "spinner", name: "spinner-03" },
    { title: "Colors", type: "spinner", name: "spinner-04" },
    { title: "Sizes", type: "spinner", name: "spinner-05" },
    {
      title: "Swirling Effect",
      type: "spinner",
      name: "spinner-06",
      credit: {
        label: "fffuel",
        link: "https://www.fffuel.co/svg-spinner/",
      },
    },
    { title: "Spinner Circle 1", type: "spinner", name: "spinner-07" },
    { title: "Spinner Circle 2", type: "spinner", name: "spinner-08" },
    { title: "Spinner Circle 3", type: "spinner", name: "spinner-09" },
    { title: "Spinner Circle 4", type: "spinner", name: "spinner-10" },
    { title: "Spinner Circle 5", type: "spinner", name: "spinner-11" },
  ],
  switch: [
    { title: "Default", type: "switch", name: "switch-01" },
    { title: "With label", type: "switch", name: "switch-02" },
    { title: "Disabled", type: "switch", name: "switch-03" },
    { title: "Colors", type: "switch", name: "switch-04" },
    { title: "Sizes", type: "switch", name: "switch-05" },
    { title: "Controlled", type: "switch", name: "switch-06" },
    { title: "Customization", type: "switch", name: "switch-07" },
  ],
  table: [
    { title: "Default", type: "table", name: "table-01" },
    { title: "Bordered", type: "table", name: "table-02" },
    { title: "Striped rows", type: "table", name: "table-03" },
    { title: "Rounded corners", type: "table", name: "table-04" },
    { title: "With pagination", type: "table", name: "table-05" },
    { title: "Sticky header", type: "table", name: "table-06" },
    { title: "Sticky columns", type: "table", name: "table-07" },
    { title: "Overflow scroll", type: "table", name: "table-08" },
    { title: "Data Table", type: "table", name: "table-09" },
    { title: "Data Table Density", type: "table", name: "table-10" },
    { title: "Columns Visibility", type: "table", name: "table-11" },
  ],
  tabs: [
    { title: "Default", type: "tabs", name: "tabs-01" },
    { title: "Underlined", type: "tabs", name: "tabs-02" },
    { title: "Separated", type: "tabs", name: "tabs-03" },
    { title: "Bordered", type: "tabs", name: "tabs-04" },
    { title: "Box", type: "tabs", name: "tabs-05" },
    { title: "Bootstrap", type: "tabs", name: "tabs-06" },
    { title: "Icon", type: "tabs", name: "tabs-07" },
    {
      title: "Mobile Navigation",
      type: "tabs",
      name: "tabs-08",
    },
    { title: "With badge", type: "tabs", name: "tabs-09" },
    { title: "Sharp", type: "tabs", name: "tabs-10" },
    { title: "Shadow", type: "tabs", name: "tabs-11" },
    { title: "Skewed", type: "tabs", name: "tabs-12" },
    { title: "Vertical", type: "tabs", name: "tabs-13" },
    {
      title: "Vertical Left Bordered",
      type: "tabs",
      name: "tabs-14",
    },
    { title: "Vertical Separated", type: "tabs", name: "tabs-15" },
    { title: "Vertical Sharp", type: "tabs", name: "tabs-16" },
    { title: "Vertical Bordered", type: "tabs", name: "tabs-17" },
    { title: "Animated Content", type: "tabs", name: "tabs-18" },
  ],
  textarea: [
    { title: "Default", type: "textarea", name: "textarea-01" },
    {
      title: "With background",
      type: "textarea",
      name: "textarea-02",
    },
    { title: "Disabled", type: "textarea", name: "textarea-03" },
    { title: "With label", type: "textarea", name: "textarea-04" },
    {
      title: "Rows",
      type: "textarea",
      name: "textarea-05",
    },
    { title: "With helper text", type: "textarea", name: "textarea-06" },
    { title: "Controlled", type: "textarea", name: "textarea-07" },
  ],
  tooltip: [
    { title: "Default", type: "tooltip", name: "tooltip-01" },
    { title: "With arrow", type: "tooltip", name: "tooltip-02" },
    { title: "Directions", type: "tooltip", name: "tooltip-03" },
    {
      title: "Disable Hoverable Content",
      type: "tooltip",
      name: "tooltip-04",
      description:
        "Prevents TooltipContent from remaining open when hovering. Disabling this has accessibility consequences.",
    },
    { title: "With delay", type: "tooltip", name: "tooltip-05" },
    {
      title: "With skip delay",
      type: "tooltip",
      name: "tooltip-06",
      description:
        "How much time a user has to enter another trigger without incurring a delay again.",
    },
    {
      title: "Portal",
      type: "tooltip",
      name: "tooltip-07",
      description: "When used, portals the content part into the body.",
    },
  ],
};
